library(metflow2)
library(tidyverse)
library(ggplot2)

### **限制單核運行**
library(doParallel)
cores <- detectCores()
cores <- detectCores()
cl <- makeCluster(cores[1]-1)
registerDoParallel(cl)

setwd("~/metflow2")
path <- file.path(".")

### **Creat `metflowClass` object**
object <- creatMetflowObject(ms1.data = c("batch1.data.csv"),
                             sample.information = "sample.info.csv",
                             path = path)

## **Align different batches**
object <- align_batch(
    object = object,
    combine.mz.tol = 15,
    combine.rt.tol = 30,
    use.int.tol = FALSE)
    
## **Missing value processing**

### **Remove noisy peaks and outlier samples**
object2 <- filter_peaks(
  object = object,
  min.fraction = 0.5,
  type = "any",
  min.subject.blank.ratio = 2,
  according.to = "class",
  which.group = "QC"
)

### **Remove outlier samples**
object2 <- filter_samples(object = object2,
                          min.fraction.peak = 0.1)
                          
### **Missing value imputation**
object2 <- imputeMV(object = object2,
                    method = "knn")
object2

## **Data normalization**
object3 <- normalizeData(object = object2, method = "svr", threads = 1)

## **Data integration**
object4 <- integrateData(object = object3, method = "qc.mean")

##draw the comprison plot:
rsd2 <- calculate_rsd(object = object2, slot = "QC")
rsd4 <- calculate_rsd(object = object4, slot = "QC")

dplyr::left_join(rsd2, rsd4, by = c("index", "name")) %>% 
  dplyr::mutate(class = dplyr::case_when(rsd.y < rsd.x ~ "Decrease",
                                         rsd.y > rsd.x ~ "Increase",
                                         rsd.y == rsd.y ~ "Equal")) %>% 
  ggplot(aes(rsd.x, rsd.y, colour = class)) +
  ggsci::scale_color_jama() +
  geom_abline(slope = 1, intercept = 0) +
  geom_point() +
  labs(x = "RSD before normalization", y = "RSD after normalization") +
  theme_bw()+
  xlim(0,200)+
  ylim(0,200)
ggsave("SVR_QC.png",dpi = 900)

rsd6 <- calculate_rsd(object = object2, slot = "Subject")
rsd8 <- calculate_rsd(object = object4, slot = "Subject")

dplyr::left_join(rsd6, rsd8, by = c("index", "name")) %>% 
  dplyr::mutate(class = dplyr::case_when(rsd.y < rsd.x ~ "Decrease",
                                         rsd.y > rsd.x ~ "Increase",
                                         rsd.y == rsd.y ~ "Equal")) %>% 
  ggplot(aes(rsd.x, rsd.y, colour = class)) +
  ggsci::scale_color_jama() +
  geom_abline(slope = 1, intercept = 0) +
  geom_point() +
  labs(x = "RSD before normalization", y = "RSD after normalization") +
  theme_bw()+
  xlim(0,200)+
  ylim(0,200)
ggsave("SVR_subject.png",dpi = 900)

## **get RSD plots after QC SVR**
RSD_results <- list()
RSD_results$name <- rsd2$name
RSD_results$QC_before <- rsd2$rsd
RSD_results$QC_after <- rsd4$rsd
RSD_results$subject_before <- rsd6$rsd
RSD_results$subject_after <- rsd8$rsd
write.csv(RSD_results,file = "./RSD_results.csv")

## **get after SVR normalization data to csv**
Data_after_integration <- data.frame(object4@ms1.data)
write.csv(Data_after_integration,file = "./Data_after_integration.csv")

Data_after_normalization <- data.frame(object3@ms1.data)
write.csv(Data_after_normalization,file = "./Data_after_normalization.csv")
